# Fix Armenian translations in i18n.js
lines = open('js/i18n.js', encoding='utf-8').readlines()

hy_start = next(i for i,l in enumerate(lines) if '  hy: {' in l)
hy_end = next(i for i in range(hy_start+1, len(lines)) if lines[i].strip() == '},')
sea13_line = next(i for i in range(hy_start, hy_end) if 'dish-sea-13' in lines[i])
print(f'Replacing lines {sea13_line+1} to {hy_end}')

new_lines = [
    "    'dish-sea-13': 'Կրակած մծուռ (250գ)',\n",
    "    'dish-sea-14': 'Մծուռ սագանակի (250գ)',\n",
    "    'dish-sea-15': 'Մծուռ / Խեցգետին (1կգ)',\n",
    "    'dish-kids-1': 'Հավի կտորներ կարտոֆիլով',\n",
    "    'dish-kids-2': 'Ձկան փայտիկներ կարտոֆիլով',\n",
    "    'dish-kids-3': 'Սպագետտի կարագով և պանրով',\n",
    "    'dish-kids-4': 'Մինի բուրգեր (2 հատ) կարտոֆիլով',\n",
    "    'dish-fishp-1': 'Դորադո (1 չափաբաժին)',\n",
    "    'dish-fishp-2': 'Ձկան ֆիլե «Armellada»',\n",
    "    'dish-fishp-3': 'Կրակած սարդին',\n",
    "    'dish-fishp-4': 'Կրակած սարդին «ամուսնացած»',\n",
    "    'dish-fishp-5': 'Սարդելա «Armellada»',\n",
    "    'dish-fishp-6': 'Տապակած անչովս',\n",
    "    'dish-fishp-7': 'Թունա շամփուր (ձեռագործ)',\n",
    "    'dish-fishkg-1': 'Դորադո',\n",
    "    'dish-fishkg-2': 'Ծովային բաս',\n",
    "    'dish-fishkg-3': 'Ատամնաձուկ',\n",
    "    'dish-fishkg-4': 'Ռոֆոս',\n",
    "    'dish-fishkg-5': 'Կարիճաձուկ',\n",
    "    'dish-fishkg-6': 'Լեզվաձուկ',\n",
    "    'dish-fishkg-7': 'Կարմիր թառ',\n",
    "    'dish-fishkg-8': 'Ձողաձուկ',\n",
    "    'dish-fishkg-9': 'Սուսերաձուկ',\n",
    "    'dish-meat-1': 'Խոզի սթեյք (350գ)',\n",
    "    'dish-meat-2': 'Տոմահոք (400-500գ)',\n",
    "    'dish-meat-3': 'Խոզի շամփուր ձեռագործ (3×120գ)',\n",
    "    'dish-meat-4': 'Հավի շամփուր ձեռագործ (3×120գ)',\n",
    "    'dish-meat-5': 'Բուրգեր (400գ)',\n",
    "    'dish-meat-6': 'Բուրգեր պանրով լցոնված (400գ)',\n",
    "    'dish-meat-7': 'Հավի ֆիլե (300գ)',\n",
    "    'dish-meat-8': 'Խոզի ֆիլե կրակածած',\n",
    "    'dish-meat-9': 'Խոզի ֆիլե սոտե',\n",
    "    'dish-meat-10': 'Հավի / Խոզի շամփուր (120գ)',\n",
    "    'dish-pasta-1': 'Ռիզոտտո սնկով',\n",
    "    'dish-pasta-2': 'Ռիզոտտո ծովամթերքով',\n",
    "    'dish-pasta-3': 'Սպագետտի Նեապոլիտանա',\n",
    "    'dish-pasta-4': 'Սպագետտի Բոլոնյա',\n",
    "    'dish-pasta-5': 'Կրեմային սպագետտի',\n",
    "    'dish-pasta-6': 'Լինգուինե ծովամթերքով',\n",
    "    'dish-pasta-7': 'Լինգուինե մծուռով',\n",
    "    'dish-pasta-8': 'Մակարոն օմարով',\n",
    "    'dish-drink-1': 'Ջուր 1լ',\n",
    "    'dish-drink-2': 'Ջուր 0.5լ',\n",
    "    'dish-drink-3': 'Գազ. / Կոլա / Սփրայթ / Հյութ / Սառը թեյ',\n",
    "    'dish-beer-1': 'Mythos / Alfa / Fix / Mamos (0.5լ)',\n",
    "    'dish-beer-2': 'Corona Extra / Kaiser (0.5լ)',\n",
    "    'dish-beer-3': 'Fix 0.0% (0.5լ)',\n",
    "    'dish-wine-1': 'Սպիտակ գինի 1լ',\n",
    "    'dish-wine-2': 'Կարմիր գինի 1լ',\n",
    "    'dish-wine-3': 'Վարդագույն կիսաքաղցր 1լ',\n",
    "    'dish-wine-4': 'Սպիտակ Moschofilero 1լ',\n",
    "    'dish-wine-5': 'Բաժակ գինի',\n",
    "    'dish-spirits-1': 'Օղի / Վիսկի (50մլ)',\n",
    "    'dish-spirits-2': 'Մաստիկա (50մլ)',\n",
    "    'dish-spirits-3': 'Մետաքսա (50մլ)',\n",
    "    'dish-ouzo-1': 'Ուզո 0.2լ',\n",
    "    'dish-ouzo-2': 'Ուզո 0.2լ (պրեմիում)',\n",
    "    'dish-ouzo-3': 'Ուզո Մինի 0.05լ',\n",
    "    'dish-ouzo-4': 'Ծիպուրո 0.2լ',\n",
    "    'dish-ouzo-5': 'Ծիպուրո 0.2լ (պրեմիում)',\n",
    "    'dish-dessert-1': 'Հալվա նարնջով և շոկոլադով',\n",
    "    'fullmenu-daily': '🕒 Ամենօրյա Ուտեստներ',\n",
    "    'fullmenu-daily-note': 'Մատուցվում է 12:00–17:00',\n",
    "    'fullmenu-appetizers': '🥣 Նախաճաշ և Սոուսներ',\n",
    "    'fullmenu-appetizers-note': 'Ձեռագործ',\n",
    "    'fullmenu-salted-note': 'Աղած Ձուկ',\n",
    "    'fullmenu-cheese': '🧀 Պանիրներ',\n",
    "    'fullmenu-salads': '🥗 Աղցաններ և Բանջարեղեն',\n",
    "    'fullmenu-salads-note': 'Աղցաններ',\n",
    "    'fullmenu-veggies-note': 'Բանջարեղեն',\n",
    "    'fullmenu-seafood': '🦪 Թարմ Ծովամթերք',\n",
    "    'fullmenu-kids': '👶 Մենյու երեխաների համար',\n",
    "    'fullmenu-fish': '🐟 Թարմ Ձուկ',\n",
    "    'fullmenu-fish-portions-note': 'Չափաբաժիններ',\n",
    "    'fullmenu-fish-kg-note': 'Գին/կգ (օրվա որս)',\n",
    "    'fullmenu-meat': '🥩 Կրակածած Միս',\n",
    "    'fullmenu-pasta': '🍝 Մակարոն և Ռիզոտտո',\n",
    "    'fullmenu-drinks': '🍹 Զովացուցիչ Ըմպելիքներ',\n",
    "    'fullmenu-beer': '🍺 Գարեջուր',\n",
    "    'fullmenu-wine': '🍷 Գինիներ',\n",
    "    'fullmenu-spirits': '🥃 Ալկոհոլային Ըմպելիքներ',\n",
    "    'fullmenu-ouzo': '🏺 Ուզո և Ծիպուրո',\n",
    "    'fullmenu-dessert': '🍊 Անուշաբույր (Նվեր)',\n",
    "    'fullmenu-dessert-note': 'Մատուցվում է անվճար ճաշի վերջում',\n",
]

lines[sea13_line:hy_end] = new_lines
open('js/i18n.js', 'w', encoding='utf-8').writelines(lines)
content = open('js/i18n.js', encoding='utf-8').read()
print('Done. Lines:', len(lines))
print('Braces OK:', content.count('{') == content.count('}'))
